# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-06-20 07:37:35
"""
import arcpy
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *

def MalheurPoderosaMod():  # MalheurPoderosaMod

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    lidar_CANOPY_HEIGHT_MODEL_MOSAIC_lyr = "D:\\Wild\\Ponderosa\\lidar_CANOPY_HEIGHT_MODEL_MOSAIC.lyr"
    MalheurNF_boundary_NAD_1983_2011_Oregon_Statewide_Lambert_Ft_Intl = "D:\\Wild\\Wild.gdb\\MalheurNF_boundary_NAD_1983_2011_Oregon_Statewide_Lambert_Ft_Intl"

    # Process: Extract by Mask (Extract by Mask) (sa)
    pondo_heightmod_1 = "D:\\Wild\\Wild.gdb\\pondo_heightmod_1"
    Extract_by_Mask = pondo_heightmod_1
    pondo_heightmod_1 = arcpy.sa.ExtractByMask(lidar_CANOPY_HEIGHT_MODEL_MOSAIC_lyr, MalheurNF_boundary_NAD_1983_2011_Oregon_Statewide_Lambert_Ft_Intl, "INSIDE", "1565601.91915348 725633.745257162 1916475.31261048 1119476.3985661 PROJCS[\"NAD_1983_2011_Oregon_Statewide_Lambert_Ft_Intl\",GEOGCS[\"GCS_NAD_1983_2011\",DATUM[\"D_NAD_1983_2011\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1312335.958005249],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-120.5],PARAMETER[\"Standard_Parallel_1\",43.0],PARAMETER[\"Standard_Parallel_2\",45.5],PARAMETER[\"Latitude_Of_Origin\",41.75],UNIT[\"Foot\",0.3048]],VERTCS[\"NAVD88_height_(ftUS)\",VDATUM[\"North_American_Vertical_Datum_1988\"],PARAMETER[\"Vertical_Shift\",0.0],PARAMETER[\"Direction\",1.0],UNIT[\"Foot_US\",0.3048006096012192]]")
    pondo_heightmod_1.save(Extract_by_Mask)


    # Process: Extract by Attributes (Extract by Attributes) (sa)
    pondo_heightmod_81_250 = "D:\\Wild\\Wild.gdb\\pondo_heightmod_81_250"
    Extract_by_Attributes = pondo_heightmod_81_250
    pondo_heightmod_81_250 = arcpy.sa.ExtractByAttributes(pondo_heightmod_1, "VALUE >= 81 And VALUE < 250")
    pondo_heightmod_81_250.save(Extract_by_Attributes)


    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    pondo_heightmod_81_250_constant = "D:\\Wild\\Wild.gdb\\pondo__heightmod_81_250_constant"
    Raster_Calculator_2_ = pondo_heightmod_81_250_constant
    pondo_heightmod_81_250_constant = 0 * "pondo_heightmod_81_250" + 1
    pondo_heightmod_81_250_constant.save(Raster_Calculator_2_)


    # Process: Int (Int) (3d)
    Int_pondo_heightmod_250_2_ = "D:\\Wild\\Wild.gdb\\Int_pondo__heightmod_250"
    arcpy.ddd.Int(in_raster_or_constant=pondo_heightmod_81_250_constant, out_raster=Int_pondo_heightmod_250_2_)
    Int_pondo_heightmod_250_2_ = arcpy.Raster(Int_pondo_heightmod_250_2_)

    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    pondo_heightmod_250_polygon = "D:\\Wild\\Wild.gdb\\pondo__heightmod_250_polygon"
    arcpy.conversion.RasterToPolygon(in_raster=Int_pondo_heightmod_250_2_, out_polygon_features=pondo_heightmod_250_polygon)

    # Process: Aggregate Polygons (3) (Aggregate Polygons) (cartography)
    pondo_heightm_100_2640_500_AggregatePoly = "D:\\Wild\\Wild.gdb\\pondo__heightm_100_2640_500_AggregatePoly"
    pondo_heightm_500_2640_1320_AggregatePoly_Tbl = "D:\\Wild\\Wild.gdb\\pondo__heightm_500_2640_1320_AggregatePoly_Tbl"
    arcpy.cartography.AggregatePolygons(in_features=pondo_heightmod_250_polygon, out_feature_class=pondo_heightm_100_2640_500_AggregatePoly, aggregation_distance="500 Feet", minimum_area="2640 SquareFeet", minimum_hole_size="1320 SquareFeet", orthogonality_option="NON_ORTHOGONAL", out_table=pondo_heightm_500_2640_1320_AggregatePoly_Tbl)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="D:\\Wild\\Wild.gdb", workspace="D:\\Wild\\Wild.gdb"):
        MalheurPoderosaMod()
