# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-06-28 16:14:54
Workflow by James Mitchell
"""
import arcpy
from arcpy.ia import *
from arcpy.sa import *


def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    OchocoWest_CANOPY_HEIGHT_MODEL_tif = arcpy.Raster("D:\\Wild\\Ochoco\\OchocoWest_CANOPY_HEIGHT_MODEL.tif")
    OchocoEast_CANOPY_HEIGHT_MODEL_tif = arcpy.Raster("D:\\Wild\\Ochoco\\OchocoEast_CANOPY_HEIGHT_MODEL.tif")
    Ochoco_gdb = "D:\\Wild\\Ochoco\\Ochoco.gdb"
    OchocoNF_Boundary_OregonLambert = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_Boundary_OregonLambert"

    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    Ochoco_CanopyHeightModel_AreaClip = arcpy.management.MosaicToNewRaster(input_rasters=[OchocoWest_CANOPY_HEIGHT_MODEL_tif, OchocoEast_CANOPY_HEIGHT_MODEL_tif], output_location=Ochoco_gdb, raster_dataset_name_with_extension="Ochoco_CanopyHeightModel_AreaClip", coordinate_system_for_the_raster="PROJCS[\"NAD_1983_2011_Oregon_Statewide_Lambert_Ft_Intl\",GEOGCS[\"GCS_NAD_1983_2011\",DATUM[\"D_NAD_1983_2011\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1312335.958005249],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-120.5],PARAMETER[\"Standard_Parallel_1\",43.0],PARAMETER[\"Standard_Parallel_2\",45.5],PARAMETER[\"Latitude_Of_Origin\",41.75],UNIT[\"Foot\",0.3048]],VERTCS[\"NAVD88_height_(ftUS)\",VDATUM[\"North_American_Vertical_Datum_1988\"],PARAMETER[\"Vertical_Shift\",0.0],PARAMETER[\"Direction\",1.0],UNIT[\"Foot_US\",0.3048006096012192]]", number_of_bands=1)[0]
    Ochoco_CanopyHeightModel_AreaClip = arcpy.Raster(Ochoco_CanopyHeightModel_AreaClip)

    # Process: Extract by Attributes (Extract by Attributes) (sa)
    OchocoNF_pondo_heightmod_82_250 = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_pondo_heightmod_82_250"
    Extract_by_Attributes = OchocoNF_pondo_heightmod_82_250
    OchocoNF_pondo_heightmod_82_250 = arcpy.sa.ExtractByAttributes(Ochoco_CanopyHeightModel_AreaClip, "VALUE >= 82 And VALUE < 250")
    OchocoNF_pondo_heightmod_82_250.save(Extract_by_Attributes)


    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    OchocoNF_pondo_heightmod_82_250_constant = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_pondo__heightmod_82_250_constant"
    Raster_Calculator_2_ = OchocoNF_pondo_heightmod_82_250_constant
    OchocoNF_pondo_heightmod_82_250_constant = 0 * OchocoNF_pondo_heightmod_82_250 + 1
    OchocoNF_pondo_heightmod_82_250_constant.save(Raster_Calculator_2_)


    # Process: Int (Int) (3d)
    OchocoNF_Int_pondo_heightmod_250 = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_Int_pondo__heightmod_250"
    arcpy.ddd.Int(in_raster_or_constant=OchocoNF_pondo_heightmod_82_250_constant, out_raster=OchocoNF_Int_pondo_heightmod_250)
    OchocoNF_Int_pondo_heightmod_250 = arcpy.Raster(OchocoNF_Int_pondo_heightmod_250)

    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    OchocoNF_pondo_heightmod_250_polygon = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_pondo__heightmod_250_polygon"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=OchocoNF_Int_pondo_heightmod_250, out_polygon_features=OchocoNF_pondo_heightmod_250_polygon)

    # Process: Aggregate Polygons (Aggregate Polygons) (cartography)
    OchocoNF_pondo_100_2640_1320_AggregatePoly = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_pondo_100_2640_1320_AggregatePoly"
    OchocoNF_pondo_100_2640_1320_AggregatePoly_Tbl = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_pondo_100_2640_1320_AggregatePoly_Tbl"
    arcpy.cartography.AggregatePolygons(in_features=OchocoNF_pondo_heightmod_250_polygon, out_feature_class=OchocoNF_pondo_100_2640_1320_AggregatePoly, aggregation_distance="100 Feet", minimum_area="2640 SquareFeetUS", minimum_hole_size="1320 SquareFeetUS", out_table=OchocoNF_pondo_100_2640_1320_AggregatePoly_Tbl)

    # Process: Extract by Mask (Extract by Mask) (sa)
    Ochoco_CanopyMod_Mask = "D:\\Wild\\Ochoco\\Ochoco.gdb\\Ochoco_CanopyMod_Mask"
    Extract_by_Mask = Ochoco_CanopyMod_Mask
    Ochoco_CanopyMod_Mask = arcpy.sa.ExtractByMask("", OchocoNF_Boundary_OregonLambert, "INSIDE", "1205855.25524935 676136.252296582 1640951.69717848 1025442.39698163 PROJCS[\"NAD_1983_2011_Oregon_Statewide_Lambert_Ft_Intl\",GEOGCS[\"GCS_NAD_1983_2011\",DATUM[\"D_NAD_1983_2011\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1312335.958005249],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-120.5],PARAMETER[\"Standard_Parallel_1\",43.0],PARAMETER[\"Standard_Parallel_2\",45.5],PARAMETER[\"Latitude_Of_Origin\",41.75],UNIT[\"Foot\",0.3048]],VERTCS[\"NAVD88_height_(ftUS)\",VDATUM[\"North_American_Vertical_Datum_1988\"],PARAMETER[\"Vertical_Shift\",0.0],PARAMETER[\"Direction\",1.0],UNIT[\"Foot_US\",0.3048006096012192]]")
    Ochoco_CanopyMod_Mask.save(Extract_by_Mask)


    # Process: Raster Domain (Raster Domain) (3d)
    Ochoco_CanopyMod_RasterDomain = "D:\\Wild\\Ochoco\\Ochoco.gdb\\Ochoco_CanopyMod_RasterDomain"
    arcpy.ddd.RasterDomain(in_raster=Ochoco_CanopyMod_Mask, out_feature_class=Ochoco_CanopyMod_RasterDomain, out_geometry_type="POLYGON")

    # Process: Erase (Erase) (analysis)
    Ochoco_NoLidarData = "D:\\Wild\\Ochoco\\Ochoco.gdb\\Ochoco_NoLidarData"
    arcpy.analysis.Erase(in_features=OchocoNF_Boundary_OregonLambert, erase_features=Ochoco_CanopyMod_RasterDomain, out_feature_class=Ochoco_NoLidarData)

    # Process: Aggregate Polygons (2) (Aggregate Polygons) (cartography)
    OchocoNF_pondo_100_2640_500_AggregatePoly = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_pondo_100_2640_500_AggregatePoly"
    OchocoNF_pondo_100_2640_500_AggregatePoly_Tbl = "D:\\Wild\\Ochoco\\Ochoco.gdb\\OchocoNF_pondo_100_2640_500_AggregatePoly_Tbl"
    arcpy.cartography.AggregatePolygons(in_features=OchocoNF_pondo_heightmod_250_polygon, out_feature_class=OchocoNF_pondo_100_2640_500_AggregatePoly, aggregation_distance="100 Feet", minimum_area="2640 SquareFeet", out_table=OchocoNF_pondo_100_2640_500_AggregatePoly_Tbl, aggregate_field="GRIDCODE")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="D:\\Wild\\Ochoco\\Ochoco.gdb", workspace="D:\\Wild\\Ochoco\\Ochoco.gdb"):
        Model()
